project : Carta.class Mazzo.class Mano.class Campo.class Gestore.class Giocatore.class GiocatoreCPU.class GiocatoreUmano.class Main.class

Carta.class : Carta.java
	javac Carta.java

Mazzo.class : Mazzo.java
	javac Mazzo.java

Mano.class : Mano.java
	javac Mano.java

Campo.class : Campo.java
	javac Campo.java

Gestore.class : Gestore.java
	javac Gestore.java

Giocatore.class : Giocatore.java
	javac Giocatore.java

GiocatoreCPU.class : GiocatoreCPU.java
	javac GiocatoreCPU.java

GiocatoreUmano.class : GiocatoreUmano.java
	javac GiocatoreUmano.java

Main.class : Main.java
	javac Main.java